/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
    Tset: typeof import('./src/components/Tset.vue')['default']
  }
}
